---

- name: create managed zone
  gcdns_zone: 
    zone: "{{ gcloud_managed_zone }}"
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    project_id: "{{ project_id }}"     
    
- name: retrieve master public ip
  shell: gcloud compute addresses list --format json --filter name={{ gcloud_env }}-master-external
  register: master_external
  changed_when: false     

- name: add master public dns entry
  gcdns_record:
    record: "{{ gcloud_master_external_fqdn }}"
    zone: "{{ gcloud_managed_zone }}"
    type: A
    value: "{{ (master_external.stdout | from_json)[0].address }}"
    overwrite: true
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    project_id: "{{ project_id }}"    
    
- name: retrieve master internal ip
  shell: gcloud compute forwarding-rules list --format json --filter name={{ gcloud_env }}-master-internal-fwr
  register: master_internal
  changed_when: false        
    
- name: add master internal dns entry
  gcdns_record:
    record: "{{ gcloud_master_internal_fqdn }}"
    zone: "{{ gcloud_managed_zone }}"
    type: A
    value: "{{ (master_internal.stdout | from_json)[0].IPAddress }}"
    overwrite: true
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    project_id: "{{ project_id }}"    
    
- name: retrieve master public ip
  shell: gcloud compute addresses list --format json --filter name={{ gcloud_env }}-infranode-external
  register: infranode_external
  changed_when: false    
    
- name: add infranode dns entry
  gcdns_record:
    record: "{{ gcloud_infranode_wildcard_fqdn }}"
    zone: "{{ gcloud_managed_zone }}"
    type: A
    value: "{{ (infranode_external.stdout | from_json)[0].address }}"
    overwrite: true
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    project_id: "{{ project_id }}"    
 
