---

# default name prefix
casl_instances:
  masters:
    name_prefix: master
  appnodes:
    name_prefix: node
  infranodes:
    name_prefix: infranode

# default instance flavors
casl_instances:
  masters:
    flavor: n1-standard-2
  appnodes:
    flavor: n1-standard-2
  infranodes:
    flavor: n1-standard-2

# default preemptibility
casl_instances:
  masters:
    preemptible: false
  appnodes:
    preemptible: false
  infranodes:
    preemptible: false 

# default docker volume size
casl_instances:
  masters:
    docker_volume_size: 10
  appnodes:
    docker_volume_size: 50
  infranodes:
    docker_volume_size: 20

# default image name
casl_instances:
  image_name: rhel7
